version: 2

project_name: azctl

builds:
  - id: azctl
    main: ./cmd/azctl
    binary: azctl
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}}"

archives:
  - format: binary
    name_template: "azctl_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: amd64
      arm64: arm64

release:
  github:
    owner: furiatona
    name: azctl