name: ci

on:
  pull_request:
    branches: [ main ]
  push:
    tags:
      - 'v*.*.*'

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - run: make test

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Build binaries
        run: make release
      - name: Upload to temp directory
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          password: ${{ secrets.CPANEL_PASS }}
          port: ${{ secrets.CPANEL_PORT }}
          source: "dist/azctl_*"
          target: "/home/${{ secrets.CPANEL_USER }}/subdomains/dl.furiatona.dev/temp"
      - name: Move files to correct location
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.CPANEL_PORT }} ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }} << 'EOF'
            # Create version directory
            mkdir -p /home/${{ secrets.CPANEL_USER }}/subdomains/dl.furiatona.dev/azctl/$VERSION
            
            # Move files from temp to version directory
            mv /home/${{ secrets.CPANEL_USER }}/subdomains/dl.furiatona.dev/temp/azctl_* /home/${{ secrets.CPANEL_USER }}/subdomains/dl.furiatona.dev/azctl/$VERSION/
            
            # Clean up temp directory
            rmdir /home/${{ secrets.CPANEL_USER }}/subdomains/dl.furiatona.dev/temp
          EOF
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          files: dist/*