name: ci

on:
  pull_request:
    branches: [ main ]
  push:
    tags:
      - 'v*.*.*'

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - run: make test

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Build binaries
        run: make release
      - name: Upload to temp directory
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          password: ${{ secrets.CPANEL_PASS }}
          port: ${{ secrets.CPANEL_PORT }}
          source: "dist/*"
          target: "/home/${{ secrets.CPANEL_USER }}/subdomains/dl.furiatona.dev/temp"
      - name: Create version directory and move files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          password: ${{ secrets.CPANEL_PASS }}
          port: ${{ secrets.CPANEL_PORT }}
          script: |
            VERSION=${GITHUB_REF#refs/tags/}
            cd /home/${{ secrets.CPANEL_USER }}/subdomains/dl.furiatona.dev
            rm -rf azctl/$VERSION && mkdir -p azctl/$VERSION
            mv temp/dist/azctl_* azctl/$VERSION/
            rm -rf temp
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          files: dist/*